blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: http://localhost:3000/docs
    about: Check the API documentation for usage examples and endpoint details
  - name: 💬 GitHub Discussions
    url: https://github.com/markcoleman/Aggregator-the-agitator/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/markcoleman/Aggregator-the-agitator/security/advisories/new
    about: Report security vulnerabilities privately