name: Question / Support
description: Ask a question or get support
title: "[Question]: "
labels: ["question", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reaching out! Please provide as much detail as possible about your question or support need.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: question-type
    attributes:
      label: Type of Question
      description: What type of question or support do you need?
      options:
        - "General Usage"
        - "API Documentation"
        - "FDX Specification"
        - "Authentication / JWT"
        - "Development Setup"
        - "Testing"
        - "Deployment"
        - "Performance"
        - "Security"
        - "Other"
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please describe your question or what you need help with
      placeholder: I need help with...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Please provide any relevant context or background information
      placeholder: I'm trying to... and I've already tried...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the FDX Resource API are you using?
      placeholder: ex. v1.0.0 or commit hash
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment are you working in?
      options:
        - Development (local)
        - Production
        - Docker container
        - CI/CD pipeline
        - Other
    validations:
      required: false

  - type: textarea
    id: attempted-solutions
    attributes:
      label: What have you tried?
      description: Please describe what you've already attempted to solve this
      placeholder: I've tried...
    validations:
      required: false

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other information that might be helpful
      placeholder: Screenshots, error messages, configuration files, etc.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true