name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v5

    - name: Enable Corepack
      run: corepack enable

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Type check
      run: pnpm typecheck

    - name: Lint
      run: pnpm lint

    - name: Format check
      run: pnpm format:check

    - name: Build
      run: pnpm build

    - name: Test
      run: pnpm test:ci

    - name: Test Coverage
      run: pnpm test:coverage
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: success()
      with:
        fail_ci_if_error: false